engines:
  fixme:
    enabled: false
  eslint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.erb"
  - "**.js"
  - "**.rb"
exclude_paths:
- "assets/javascripts/"
- "assets/stylesheets/jquery.*"
