Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  TargetRailsVersion: 4.2

Metrics/AbcSize:
  Max: 65

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 20

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/Documentation:
  Enabled: false
