icons:
  500px: f26e
  accessible_icon: f368
  accusoft: f369
  adn: f170
  adversal: f36a
  affiliatetheme: f36b
  algolia: f36c
  amazon: f270
  amilia: f36d
  android: f17b
  angellist: f209
  angrycreative: f36e
  angular: f420
  app_store: f36f
  app_store_ios: f370
  apper: f371
  apple: f179
  apple_pay: f415
  asymmetrik: f372
  audible: f373
  autoprefixer: f41c
  avianex: f374
  aviato: f421
  aws: f375
  bandcamp: f2d5
  behance: f1b4
  behance_square: f1b5
  bimobject: f378
  bitbucket: f171
  bitcoin: f379
  bity: f37a
  black_tie: f27e
  blackberry: f37b
  blogger: f37c
  blogger_b: f37d
  bluetooth: f293
  bluetooth_b: f294
  btc: f15a
  buromobelexperte: f37f
  buysellads: f20d
  cc_amex: f1f3
  cc_apple_pay: f416
  cc_diners_club: f24c
  cc_discover: f1f2
  cc_jcb: f24b
  cc_mastercard: f1f1
  cc_paypal: f1f4
  cc_stripe: f1f5
  cc_visa: f1f0
  centercode: f380
  chrome: f268
  cloudscale: f383
  cloudsmith: f384
  cloudversify: f385
  codepen: f1cb
  codiepie: f284
  connectdevelop: f20e
  contao: f26d
  cpanel: f388
  creative_commons: f25e
  css3: f13c
  css3_alt: f38b
  cuttlefish: f38c
  d_and_d: f38d
  dashcube: f210
  delicious: f1a5
  deploydog: f38e
  deskpro: f38f
  deviantart: f1bd
  digg: f1a6
  digital_ocean: f391
  discord: f392
  discourse: f393
  dochub: f394
  docker: f395
  draft2digital: f396
  dribbble: f17d
  dribbble_square: f397
  dropbox: f16b
  dropbox_alt: f398
  drupal: f1a9
  dyalog: f399
  earlybirds: f39a
  edge: f282
  ember: f423
  empire: f1d1
  envira: f299
  erlang: f39d
  etsy: f2d7
  expeditedssl: f23e
  facebook: f09a
  facebook_f: f39e
  facebook_messenger: f39f
  facebook_square: f082
  firefox: f269
  first_order: f2b0
  firstdraft: f3a1
  flickr: f16e
  fly: f417
  font_awesome: f2b4
  font_awesome_alt: f35c
  fonticons: f280
  fonticons_fi: f3a2
  fort_awesome: f286
  fort_awesome_alt: f3a3
  forumbee: f211
  foursquare: f180
  free_code_camp: f2c5
  freebsd: f3a4
  get_pocket: f265
  gg: f260
  gg_circle: f261
  git: f1d3
  git_square: f1d2
  github: f09b
  github_alt: f113
  github_square: f092
  gitkraken: f3a6
  gitlab: f296
  gitter: f426
  glide: f2a5
  glide_g: f2a6
  gofore: f3a7
  goodreads: f3a8
  goodreads_g: f3a9
  google: f1a0
  google_drive: f3aa
  google_play: f3ab
  google_plus: f2b3
  google_plus_g: f0d5
  google_plus_square: f0d4
  google_wallet: f1ee
  gratipay: f184
  grav: f2d6
  gripfire: f3ac
  grunt: f3ad
  gulp: f3ae
  hacker_news: f1d4
  hacker_news_square: f3af
  hire_a_helper: f3b0
  hooli: f427
  hotjar: f3b1
  houzz: f27c
  html5: f13b
  hubspot: f3b2
  imdb: f2d8
  instagram: f16d
  internet_explorer: f26b
  ioxhost: f208
  itunes: f3b4
  itunes_note: f3b5
  jenkins: f3b6
  joget: f3b7
  joomla: f1aa
  js: f3b8
  js_square: f3b9
  jsfiddle: f1cc
  keycdn: f3ba
  kickstarter: f3bb
  kickstarter_k: f3bc
  laravel: f3bd
  lastfm: f202
  lastfm_square: f203
  leanpub: f212
  less: f41d
  line: f3c0
  linkedin: f08c
  linkedin_in: f0e1
  linode: f2b8
  linux: f17c
  lyft: f3c3
  magento: f3c4
  maxcdn: f136
  medapps: f3c6
  medium: f23a
  medium_m: f3c7
  medrt: f3c8
  meetup: f2e0
  microsoft: f3ca
  mix: f3cb
  mixcloud: f289
  mizuni: f3cc
  modx: f285
  monero: f3d0
  napster: f3d2
  nintendo_switch: f418
  node: f419
  node_js: f3d3
  npm: f3d4
  ns8: f3d5
  nutritionix: f3d6
  odnoklassniki: f263
  odnoklassniki_square: f264
  opencart: f23d
  openid: f19b
  opera: f26a
  optin_monster: f23c
  osi: f41a
  page4: f3d7
  pagelines: f18c
  palfed: f3d8
  patreon: f3d9
  paypal: f1ed
  periscope: f3da
  phabricator: f3db
  phoenix_framework: f3dc
  pied_piper: f2ae
  pied_piper_alt: f1a8
  pied_piper_pp: f1a7
  pinterest: f0d2
  pinterest_p: f231
  pinterest_square: f0d3
  playstation: f3df
  product_hunt: f288
  pushed: f3e1
  python: f3e2
  qq: f1d6
  quora: f2c4
  ravelry: f2d9
  react: f41b
  rebel: f1d0
  red_river: f3e3
  reddit: f1a1
  reddit_alien: f281
  reddit_square: f1a2
  rendact: f3e4
  renren: f18b
  replyd: f3e6
  resolving: f3e7
  rocketchat: f3e8
  rockrms: f3e9
  safari: f267
  sass: f41e
  schlix: f3ea
  scribd: f28a
  searchengin: f3eb
  sellcast: f2da
  sellsy: f213
  servicestack: f3ec
  shirtsinbulk: f214
  simplybuilt: f215
  sistrix: f3ee
  skyatlas: f216
  skype: f17e
  slack: f198
  slack_hash: f3ef
  slideshare: f1e7
  snapchat: f2ab
  snapchat_ghost: f2ac
  snapchat_square: f2ad
  soundcloud: f1be
  speakap: f3f3
  spotify: f1bc
  stack_exchange: f18d
  stack_overflow: f16c
  staylinked: f3f5
  steam: f1b6
  steam_square: f1b7
  steam_symbol: f3f6
  sticker_mule: f3f7
  strava: f428
  stripe: f429
  studiovinari: f3f8
  stumbleupon: f1a4
  stumbleupon_circle: f1a3
  superpowers: f2dd
  supple: f3f9
  telegram: f2c6
  telegram_plane: f3fe
  tencent_weibo: f1d5
  themeisle: f2b2
  trello: f181
  tripadvisor: f262
  tumblr: f173
  tumblr_square: f174
  twitch: f1e8
  twitter: f099
  twitter_square: f081
  uber: f402
  uikit: f403
  uniregistry: f404
  untappd: f405
  usb: f287
  ussunnah: f407
  vaadin: f408
  viacoin: f237
  viadeo: f2a9
  viadeo_square: f2aa
  viber: f409
  vimeo: f40a
  vimeo_square: f194
  vimeo_v: f27d
  vine: f1ca
  vk: f189
  vnv: f40b
  vuejs: f41f
  weibo: f18a
  weixin: f1d7
  whatsapp: f232
  whatsapp_square: f40c
  whmcs: f40d
  wikipedia_w: f266
  windows: f17a
  wordpress: f19a
  wordpress_simple: f411
  wpbeginner: f297
  wpexplorer: f2de
  wpforms: f298
  xbox: f412
  xing: f168
  xing_square: f169
  y_combinator: f23b
  yahoo: f19e
  yandex: f413
  yandex_international: f414
  yelp: f1e9
  yoast: f2b1
  youtube: f167
