icons:
  address_book: f2b9
  address_card: f2bb
  arrow_alt_circle_down: f358
  arrow_alt_circle_left: f359
  arrow_alt_circle_right: f35a
  arrow_alt_circle_up: f35b
  bell: f0f3
  bell_slash: f1f6
  bookmark: f02e
  building: f1ad
  calendar: f133
  calendar_alt: f073
  calendar_check: f274
  calendar_minus: f272
  calendar_plus: f271
  calendar_times: f273
  caret_square_down: f150
  caret_square_left: f191
  caret_square_right: f152
  caret_square_up: f151
  chart_bar: f080
  check_circle: f058
  check_square: f14a
  circle: f111
  clipboard: f328
  clock: f017
  clone: f24d
  closed_captioning: f20a
  comment: f075
  comment_alt: f27a
  comments: f086
  compass: f14e
  copy: f0c5
  copyright: f1f9
  credit_card: f09d
  dot_circle: f192
  edit: f044
  envelope: f0e0
  envelope_open: f2b6
  eye_slash: f070
  file: f15b
  file_alt: f15c
  file_archive: f1c6
  file_audio: f1c7
  file_code: f1c9
  file_excel: f1c3
  file_image: f1c5
  file_pdf: f1c1
  file_powerpoint: f1c4
  file_video: f1c8
  file_word: f1c2
  flag: f024
  folder: f07b
  folder_open: f07c
  frown: f119
  futbol: f1e3
  gem: f3a5
  hand_lizard: f258
  hand_paper: f256
  hand_peace: f25b
  hand_point_down: f0a7
  hand_point_left: f0a5
  hand_point_right: f0a4
  hand_point_up: f0a6
  hand_pointer: f25a
  hand_rock: f255
  hand_scissors: f257
  hand_spock: f259
  handshake: f2b5
  hdd: f0a0
  heart: f004
  hospital: f0f8
  hourglass: f254
  id_badge: f2c1
  id_card: f2c2
  image: f03e
  images: f302
  keyboard: f11c
  lemon: f094
  life_ring: f1cd
  lightbulb: f0eb
  list_alt: f022
  map: f279
  meh: f11a
  minus_square: f146
  money_bill_alt: f3d1
  moon: f186
  newspaper: f1ea
  object_group: f247
  object_ungroup: f248
  paper_plane: f1d8
  pause_circle: f28b
  play_circle: f144
  plus_square: f0fe
  question_circle: f059
  registered: f25d
  save: f0c7
  share_square: f14d
  smile: f118
  snowflake: f2dc
  square: f0c8
  star: f005
  star_half: f089
  sticky_note: f249
  stop_circle: f28d
  sun: f185
  thumbs_down: f165
  thumbs_up: f164
  times_circle: f057
  trash_alt: f2ed
  user: f007
  user_circle: f2bd
  window_close: f410
  window_maximize: f2d0
  window_restore: f2d2
