icons:
  address_book: f2b9
  address_card: f2bb
  adjust: f042
  align_center: f037
  align_justify: f039
  align_left: f036
  align_right: f038
  ambulance: f0f9
  american_sign_language_interpreting: f2a3
  anchor: f13d
  angle_double_down: f103
  angle_double_left: f100
  angle_double_right: f101
  angle_double_up: f102
  angle_down: f107
  angle_left: f104
  angle_right: f105
  angle_up: f106
  archive: f187
  arrow_alt_circle_down: f358
  arrow_alt_circle_left: f359
  arrow_alt_circle_right: f35a
  arrow_alt_circle_up: f35b
  arrow_circle_down: f0ab
  arrow_circle_left: f0a8
  arrow_circle_right: f0a9
  arrow_circle_up: f0aa
  arrow_down: f063
  arrow_left: f060
  arrow_right: f061
  arrow_up: f062
  arrows_alt: f0b2
  arrows_alt_h: f337
  arrows_alt_v: f338
  assistive_listening_systems: f2a2
  asterisk: f069
  at: f1fa
  audio_description: f29e
  backward: f04a
  balance_scale: f24e
  ban: f05e
  barcode: f02a
  bars: f0c9
  bath: f2cd
  battery_empty: f244
  battery_full: f240
  battery_half: f242
  battery_quarter: f243
  battery_three_quarters: f241
  bed: f236
  beer: f0fc
  bell: f0f3
  bell_slash: f1f6
  bicycle: f206
  binoculars: f1e5
  birthday_cake: f1fd
  blind: f29d
  bold: f032
  bolt: f0e7
  bomb: f1e2
  book: f02d
  bookmark: f02e
  braille: f2a1
  briefcase: f0b1
  bug: f188
  building: f1ad
  bullhorn: f0a1
  bullseye: f140
  bus: f207
  calculator: f1ec
  calendar: f133
  calendar_alt: f073
  calendar_check: f274
  calendar_minus: f272
  calendar_plus: f271
  calendar_times: f273
  camera: f030
  camera_retro: f083
  car: f1b9
  caret_down: f0d7
  caret_left: f0d9
  caret_right: f0da
  caret_square_down: f150
  caret_square_left: f191
  caret_square_right: f152
  caret_square_up: f151
  caret_up: f0d8
  cart_arrow_down: f218
  cart_plus: f217
  certificate: f0a3
  chart_area: f1fe
  chart_bar: f080
  chart_line: f201
  chart_pie: f200
  check: f00c
  check_circle: f058
  check_square: f14a
  chevron_circle_down: f13a
  chevron_circle_left: f137
  chevron_circle_right: f138
  chevron_circle_up: f139
  chevron_down: f078
  chevron_left: f053
  chevron_right: f054
  chevron_up: f077
  child: f1ae
  circle: f111
  circle_notch: f1ce
  clipboard: f328
  clock: f017
  clone: f24d
  closed_captioning: f20a
  cloud: f0c2
  cloud_download_alt: f381
  cloud_upload_alt: f382
  code: f121
  code_branch: f126
  coffee: f0f4
  cog: f013
  cogs: f085
  columns: f0db
  comment: f075
  comment_alt: f27a
  comments: f086
  compass: f14e
  compress: f066
  copy: f0c5
  copyright: f1f9
  credit_card: f09d
  crop: f125
  crosshairs: f05b
  cube: f1b2
  cubes: f1b3
  cut: f0c4
  database: f1c0
  deaf: f2a4
  desktop: f108
  dollar_sign: f155
  dot_circle: f192
  download: f019
  edit: f044
  eject: f052
  ellipsis_h: f141
  ellipsis_v: f142
  envelope: f0e0
  envelope_open: f2b6
  envelope_square: f199
  eraser: f12d
  euro_sign: f153
  exchange_alt: f362
  exclamation: f12a
  exclamation_circle: f06a
  exclamation_triangle: f071
  expand: f065
  expand_arrows_alt: f31e
  external_link_alt: f35d
  external_link_square_alt: f360
  eye: f06e
  eye_dropper: f1fb
  eye_slash: f070
  fast_backward: f049
  fast_forward: f050
  fax: f1ac
  female: f182
  fighter_jet: f0fb
  file: f15b
  file_alt: f15c
  file_archive: f1c6
  file_audio: f1c7
  file_code: f1c9
  file_excel: f1c3
  file_image: f1c5
  file_pdf: f1c1
  file_powerpoint: f1c4
  file_video: f1c8
  file_word: f1c2
  film: f008
  filter: f0b0
  fire: f06d
  fire_extinguisher: f134
  flag: f024
  flag_checkered: f11e
  flask: f0c3
  folder: f07b
  folder_open: f07c
  font: f031
  forward: f04e
  frown: f119
  futbol: f1e3
  gamepad: f11b
  gavel: f0e3
  gem: f3a5
  genderless: f22d
  gift: f06b
  glass_martini: f000
  globe: f0ac
  graduation_cap: f19d
  h_square: f0fd
  hand_lizard: f258
  hand_paper: f256
  hand_peace: f25b
  hand_point_down: f0a7
  hand_point_left: f0a5
  hand_point_right: f0a4
  hand_point_up: f0a6
  hand_pointer: f25a
  hand_rock: f255
  hand_scissors: f257
  hand_spock: f259
  handshake: f2b5
  hashtag: f292
  hdd: f0a0
  heading: f1dc
  headphones: f025
  heart: f004
  heartbeat: f21e
  history: f1da
  home: f015
  hospital: f0f8
  hourglass: f254
  hourglass_end: f253
  hourglass_half: f252
  hourglass_start: f251
  i_cursor: f246
  id_badge: f2c1
  id_card: f2c2
  image: f03e
  images: f302
  inbox: f01c
  indent: f03c
  industry: f275
  info: f129
  info_circle: f05a
  italic: f033
  key: f084
  keyboard: f11c
  language: f1ab
  laptop: f109
  leaf: f06c
  lemon: f094
  level_down_alt: f3be
  level_up_alt: f3bf
  life_ring: f1cd
  lightbulb: f0eb
  link: f0c1
  lira_sign: f195
  list: f03a
  list_alt: f022
  list_ol: f0cb
  list_ul: f0ca
  location_arrow: f124
  lock: f023
  long_arrow_alt_down: f309
  long_arrow_alt_left: f30a
  long_arrow_alt_right: f30b
  long_arrow_alt_up: f30c
  low_vision: f2a8
  magic: f0d0
  magnet: f076
  male: f183
  map: f279
  map_marker: f041
  map_marker_alt: f3c5
  map_pin: f276
  map_signs: f277
  mars: f222
  mars_double: f227
  mars_stroke: f229
  mars_stroke_h: f22b
  mars_stroke_v: f22a
  medkit: f0fa
  meh: f11a
  mercury: f223
  microchip: f2db
  microphone: f130
  microphone_slash: f131
  minus: f068
  minus_circle: f056
  minus_square: f146
  mobile: f10b
  mobile_alt: f3cd
  money_bill_alt: f3d1
  moon: f186
  motorcycle: f21c
  mouse_pointer: f245
  music: f001
  neuter: f22c
  newspaper: f1ea
  object_group: f247
  object_ungroup: f248
  outdent: f03b
  paint_brush: f1fc
  paper_plane: f1d8
  paperclip: f0c6
  paragraph: f1dd
  paste: f0ea
  pause: f04c
  pause_circle: f28b
  paw: f1b0
  pen_square: f14b
  pencil_alt: f303
  percent: f295
  phone: f095
  phone_square: f098
  phone_volume: f2a0
  plane: f072
  play: f04b
  play_circle: f144
  plug: f1e6
  plus: f067
  plus_circle: f055
  plus_square: f0fe
  podcast: f2ce
  pound_sign: f154
  power_off: f011
  print: f02f
  puzzle_piece: f12e
  qrcode: f029
  question: f128
  question_circle: f059
  quote_left: f10d
  quote_right: f10e
  random: f074
  recycle: f1b8
  redo: f01e
  registered: f25d
  reply: f3e5
  reply_all: f122
  retweet: f079
  road: f018
  rocket: f135
  rss: f09e
  rss_square: f143
  ruble_sign: f158
  rupee_sign: f156
  save: f0c7
  search: f002
  search_minus: f010
  search_plus: f00e
  server: f233
  share: f064
  share_alt: f1e0
  share_alt_square: f1e1
  share_square: f14d
  shekel_sign: f20b
  shield_alt: f3ed
  ship: f21a
  shopping_bag: f290
  shopping_basket: f291
  shopping_cart: f07a
  shower: f2cc
  sign_in_alt: f2f6
  sign_language: f2a7
  sign_out_alt: f2f5
  signal: f012
  sitemap: f0e8
  sliders_h: f1de
  smile: f118
  snowflake: f2dc
  sort: f0dc
  sort_alpha_down: f15d
  sort_alpha_up: f15e
  sort_amount_down: f160
  sort_amount_up: f161
  sort_down: f0dd
  sort_numeric_down: f162
  sort_numeric_up: f163
  sort_up: f0de
  space_shuttle: f197
  spinner: f110
  square: f0c8
  star: f005
  star_half: f089
  step_backward: f048
  step_forward: f051
  stethoscope: f0f1
  sticky_note: f249
  stop: f04d
  stop_circle: f28d
  street_view: f21d
  strikethrough: f0cc
  subscript: f12c
  subway: f239
  suitcase: f0f2
  sun: f185
  superscript: f12b
  sync: f021
  table: f0ce
  tablet: f10a
  tablet_alt: f3fa
  tachometer_alt: f3fd
  tag: f02b
  tags: f02c
  tasks: f0ae
  taxi: f1ba
  terminal: f120
  text_height: f034
  text_width: f035
  th: f00a
  th_large: f009
  th_list: f00b
  thermometer_empty: f2cb
  thermometer_full: f2c7
  thermometer_half: f2c9
  thermometer_quarter: f2ca
  thermometer_three_quarters: f2c8
  thumbs_down: f165
  thumbs_up: f164
  thumbtack: f08d
  ticket_alt: f3ff
  times: f00d
  times_circle: f057
  tint: f043
  toggle_off: f204
  toggle_on: f205
  trademark: f25c
  train: f238
  transgender: f224
  transgender_alt: f225
  trash: f1f8
  trash_alt: f2ed
  tree: f1bb
  trophy: f091
  truck: f0d1
  tty: f1e4
  tv: f26c
  umbrella: f0e9
  underline: f0cd
  undo: f0e2
  universal_access: f29a
  university: f19c
  unlink: f127
  unlock: f09c
  unlock_alt: f13e
  upload: f093
  user: f007
  user_circle: f2bd
  user_md: f0f0
  user_plus: f234
  user_secret: f21b
  user_times: f235
  users: f0c0
  utensil_spoon: f2e5
  utensils: f2e7
  venus: f221
  venus_double: f226
  venus_mars: f228
  video: f03d
  volume_down: f027
  volume_off: f026
  volume_up: f028
  wheelchair: f193
  wifi: f1eb
  window_close: f410
  window_maximize: f2d0
  window_minimize: f2d1
  window_restore: f2d2
  won_sign: f159
  wrench: f0ad
  yen_sign: f157
